### ISSUE TITLE
docs missing module functions; and ~ files

### ISSUE THREAD

**Issue by rainwoodman** [dkirkby/gphist#1]
Two minor issues:

- The API documentation is completely empty..

- Also there are a lot of ~ files in the repo.

**Comment by dkirkby** [comment]
I removed the ~ files in 75807b6.

**Comment by dkirkby** [comment]
Thanks for reporting the missing docs, but I'm not sure what the problem is since the following works on my laptop:
```
cd docs
make html
open _build/html/index.html
```
I will look for clues in the [readthedocs log](https://readthedocs.org/projects/gphist/builds/6053056/).

**Comment by rainwoodman** [comment]
Thanks! Perhaps it is a few missing files.

**Comment by dkirkby** [comment]
I found and fixed the problem (missing mocks for external pkgs) and the [API docs](http://gphist.readthedocs.io/en/latest/src/gphist.html) look ok to me now.
