### ISSUE TITLE
Regarding python 3.x support

### ISSUE THREAD

**Issue by purba16** [dkirkby/gphist#2]
Dear Sir,

Could you please help me with running the gphist code in python3 environment.

**Comment by dkirkby** [comment]
I am not working on 3.x migration for this pkg, but it should be straightforward and you are welcome to submit a PR. 
 Is there a specific problem you encountered?

**Comment by rekeeley** [comment]
I'm pretty sure all of the changes needed to support python3 are changing print X to print(X)

**Comment by purba16** [comment]
Thank you so much for your confirmation!
